version: '2'
services:
  angular-docker:
    container_name: angular-docker
    build: .
    command: "npm start -- --host=0.0.0.0"
    ports:
      - 4200:4200
      - 49152:49152
    volumes:
      - .:/home/app/angular-docker
      - /home/app/angular-docker/node_modules